version: '3.8'

services:
  app-builder:
    build: .
    image: crpi-rqm712svm0emwmme.cn-shanghai.personal.cr.aliyuncs.com/wang-space/pdf-ai-service:latest
    container_name: pdf-ai-builder-runner
    restart: always
    command: ["sleep", "infinity"]