services:
  my-service:
    build: .                 # 核心：告诉 Portainer 直接在本地根据上面的 Dockerfile 编译代码
    container_name: pdf-ai-service
    restart: always
    network_mode: host       # 使用 host 模式，让应用能直接通过 127.0.0.1:8500 连上本机的 Consul
    environment:
      - ENV=production
      - CONSUL_HOST=127.0.0.1
      - CONSUL_PORT=8500